### ISSUE TITLE
Invalid name "0" - Order Email Delivery Job 

### ISSUE THREAD

**Issue by liviusirbulescu** [aimeos/ai-controller-jobs#42]
Hi Guys,

I'm not sure at this point if this is a bug or just a missing config

**Environment**
1. Version: 2022.04.3
2. Operating system: Ubuntu 20.04.4, PHP: 8.1.6

**Describe the bug**
Emails are not sent when running aimeos:job order/email/delivery on a standard aimeos/aimeos installation
```
php artisan aimeos:job order/email/delivery
Invalid name "0"
#0 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Criteria/Expression/Combine/SQL.php(71): Aimeos\Base\Criteria\Expression\Compare\Base->toSource()
aimeos/aimeos-laravel#1 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Criteria/Expression/Combine/SQL.php(71): Aimeos\Base\Criteria\Expression\Combine\SQL->toSource()
aimeos/aimeos-laravel#2 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Criteria/Expression/Combine/SQL.php(85): Aimeos\Base\Criteria\Expression\Combine\SQL->toSource()
aimeos/aimeos-laravel#3 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Criteria/SQL.php(129): Aimeos\Base\Criteria\Expression\Combine\SQL->toSource()
aimeos/aimeos-laravel#4 /var/www/aimeos/vendor/aimeos/aimeos-core/src/MShop/Common/Manager/Base.php(777): Aimeos\Base\Criteria\SQL->getConditionSource()
aimeos/aimeos-laravel#5 /var/www/aimeos/vendor/aimeos/aimeos-core/src/MShop/Common/Manager/Base.php(839): Aimeos\MShop\Common\Manager\Base->getSQLReplacements()
aimeos/aimeos-laravel#6 /var/www/aimeos/vendor/aimeos/aimeos-core/src/MShop/Order/Manager/Standard.php(795): Aimeos\MShop\Common\Manager\Base->searchItemsBase()
aimeos/aimeos-laravel#7 /var/www/aimeos/vendor/aimeos/aimeos-core/src/MShop/Common/Manager/Decorator/Depth.php(59): Aimeos\MShop\Order\Manager\Standard->search()
aimeos/aimeos-laravel#8 /var/www/aimeos/vendor/aimeos/aimeos-core/src/MShop/Common/Manager/Decorator/Lazy.php(36): Aimeos\MShop\Common\Manager\Decorator\Depth->search()
aimeos/aimeos-laravel#9 /var/www/aimeos/vendor/aimeos/map/src/Map.php(4309): Aimeos\MShop\Common\Manager\Decorator\Lazy->Aimeos\MShop\Common\Manager\Decorator\{closure}()
aimeos/aimeos-laravel#10 /var/www/aimeos/vendor/aimeos/map/src/Map.php(4372): Aimeos\Map->array()
aimeos/aimeos-laravel#11 /var/www/aimeos/vendor/aimeos/map/src/Map.php(120): Aimeos\Map->list()
aimeos/aimeos-laravel#12 /var/www/aimeos/vendor/aimeos/ai-controller-jobs/src/Controller/Jobs/Order/Email/Delivery/Standard.php(202): Aimeos\Map->__call()
aimeos/aimeos-laravel#13 /var/www/aimeos/vendor/aimeos/ai-controller-jobs/src/Controller/Jobs/Order/Email/Delivery/Standard.php(127): Aimeos\Controller\Jobs\Order\Email\Delivery\Standard->notify()
aimeos/aimeos-laravel#14 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(54): Aimeos\Controller\Jobs\Order\Email\Delivery\Standard->run()
aimeos/aimeos-laravel#15 [internal function]: Aimeos\Shop\Command\JobsCommand->Aimeos\Shop\Command\{closure}()
aimeos/aimeos-laravel#16 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(181): call_user_func_array()
aimeos/aimeos-laravel#17 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(116): Aimeos\Base\Process\Pcntl->exec()
aimeos/aimeos-laravel#18 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Decorator/Check.php(61): Aimeos\Base\Process\Pcntl->start()
aimeos/aimeos-laravel#19 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(63): Aimeos\Base\Process\Decorator\Check->start()
aimeos/aimeos-laravel#20 [internal function]: Aimeos\Shop\Command\JobsCommand->Aimeos\Shop\Command\{closure}()
aimeos/aimeos-laravel#21 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(181): call_user_func_array()
aimeos/aimeos-laravel#22 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(116): Aimeos\Base\Process\Pcntl->exec()
aimeos/aimeos-laravel#23 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Decorator/Check.php(61): Aimeos\Base\Process\Pcntl->start()
aimeos/aimeos-laravel#24 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/AbstractCommand.php(67): Aimeos\Base\Process\Decorator\Check->start()
aimeos/aimeos-laravel#25 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(69): Aimeos\Shop\Command\AbstractCommand->exec()
aimeos/aimeos-laravel#26 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Aimeos\Shop\Command\JobsCommand->handle()
aimeos/aimeos-laravel#27 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
aimeos/aimeos-laravel#28 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
aimeos/aimeos-laravel#29 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
aimeos/aimeos-laravel#30 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()
aimeos/aimeos-laravel#31 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
aimeos/aimeos-laravel#32 /var/www/aimeos/vendor/symfony/console/Command/Command.php(291): Illuminate\Console\Command->execute()
aimeos/aimeos-laravel#33 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
aimeos/aimeos-laravel#34 /var/www/aimeos/vendor/symfony/console/Application.php(989): Illuminate\Console\Command->run()
aimeos/aimeos-laravel#35 /var/www/aimeos/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
aimeos/aimeos-laravel#36 /var/www/aimeos/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
aimeos/aimeos-laravel#37 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
aimeos/aimeos-laravel#38 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
aimeos/aimeos-laravel#39 /var/www/aimeos/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
aimeos/aimeos-laravel#40 {main}Process (PID "18964") failed with status "256"
```

**To Reproduce**
Create an order in a standard aimeos/aimeos installation and then run php artisan aimeos:job order/email/delivery

**Expected behavior**
Order delivery emails sent

**Additional context**
.ENV content
`SHOP_MULTILOCALE=true
SHOP_MULTISHOP=false
SHOP_REGISTRATION=false
SHOP_PERMISSION=`

Content of $types array when this is failing
Aimeos\Base\Criteria\Expression\Compare\Base::toSource
```
$types = [
  "locale.language.id" => 4
  "locale.language.label" => 4
  "locale.language.code" => 4
  "locale.language.status" => 2
  "locale.language.ctime" => 4
  "locale.language.mtime" => 4
  "locale.language.editor" => 4
  1 => 2
]
```

mshop_order table content
| id | siteid | baseid | relatedid | channel | datepayment         | datedelivery | statuspayment | statusdelivery | cdate      | cmonth  | cweek   | cwday | chour | mtime               | ctime               | editor      |
|----|--------|--------|-----------|---------|---------------------|--------------|---------------|----------------|------------|---------|---------|-------|-------|---------------------|---------------------|-------------|
|  9 | 1.     |      9 |           |         | 2022-05-24 11:14:32 |              |             5 |              1 | 2022-05-24 | 2022-05 | 2022-21 | 2     | 11    | 2022-05-24 11:15:00 | 2022-05-24 11:14:32 | aimeos:jobs |

mshop_order_status table content
| id | siteid | parentid | type            | value | mtime               | ctime               | editor      |
|----|--------|----------|-----------------|-------|---------------------|---------------------|-------------|
| 29 | 1.     |        9 | stock-update    | 1     | 2022-05-24 11:14:32 | 2022-05-24 11:14:32 | LS          |
| 30 | 1.     |        9 | coupon-update   | 1     | 2022-05-24 11:14:32 | 2022-05-24 11:14:32 | LS          |
| 31 | 1.     |        9 | status-payment  | 5     | 2022-05-24 11:14:32 | 2022-05-24 11:14:32 | LS          |
| 32 | 1.     |        9 | status-delivery | 1     | 2022-05-24 11:15:00 | 2022-05-24 11:15:00 | aimeos:jobs |

**Comment by aimeos** [comment]
Thanks for the report!

Can you please try again after updating to:
```
composer req aimeos/ai-controller-jobs:2022.04.x-dev
```

**Comment by liviusirbulescu** [comment]
Thanks for the quick reply !

I can confirm this fixed the invalid name issue and no errors are returned in the console. I'm now getting No value for key "addressItem" in aimeos logs on 2022.04.x-dev, see below trace.

```
Error while trying to send payment e-mail for order ID "9" and status "5": No value for key "addressItem" found
#0 /var/www/aimeos/vendor/aimeos/ai-controller-jobs/src/Controller/Jobs/Order/Email/Payment/Standard.php(321): Aimeos\Base\View\Standard->__get()
#1 /var/www/aimeos/vendor/aimeos/ai-controller-jobs/src/Controller/Jobs/Order/Email/Payment/Standard.php(216): Aimeos\Controller\Jobs\Order\Email\Payment\Standard->send()
#2 /var/www/aimeos/vendor/aimeos/ai-controller-jobs/src/Controller/Jobs/Order/Email/Payment/Standard.php(128): Aimeos\Controller\Jobs\Order\Email\Payment\Standard->notify()
#3 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(54): Aimeos\Controller\Jobs\Order\Email\Payment\Standard->run()
#4 [internal function]: Aimeos\Shop\Command\JobsCommand->Aimeos\Shop\Command\closure()
#5 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(181): call_user_func_array()
#6 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(116): Aimeos\Base\Process\Pcntl->exec()
#7 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Decorator/Check.php(61): Aimeos\Base\Process\Pcntl->start()
#8 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(63): Aimeos\Base\Process\Decorator\Check->start()
#9 [internal function]: Aimeos\Shop\Command\JobsCommand->Aimeos\Shop\Command\closure()
#10 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(181): call_user_func_array()
#11 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(116): Aimeos\Base\Process\Pcntl->exec()
#12 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Decorator/Check.php(61): Aimeos\Base\Process\Pcntl->start()
#13 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/AbstractCommand.php(67): Aimeos\Base\Process\Decorator\Check->start()
#14 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(69): Aimeos\Shop\Command\AbstractCommand->exec()
#15 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Aimeos\Shop\Command\JobsCommand->handle()
#16 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\closure()
#17 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#18 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#19 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()
#20 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#21 /var/www/aimeos/vendor/symfony/console/Command/Command.php(291): Illuminate\Console\Command->execute()
#22 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#23 /var/www/aimeos/vendor/symfony/console/Application.php(989): Illuminate\Console\Command->run()
#24 /var/www/aimeos/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#25 /var/www/aimeos/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#26 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#27 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#28 /var/www/aimeos/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#29 main
```

**Comment by aimeos** [comment]
We've fixed that problem too. Please update and try again.

**Comment by liviusirbulescu** [comment]
Missing address is fixed, $target is now undefined in templates/order/email/payment/html.php

```
Error while trying to send payment e-mail for order ID "9" and status "5": Undefined variable $target
#0 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/aimeos/vendor/aimeos/ai-controller-jobs/templates/order/email/payment/html.php(130): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\closure()
#2 /var/www/aimeos/vendor/aimeos/aimeos-base/src/View/Standard.php(281): include('...')
#3 /var/www/aimeos/vendor/aimeos/aimeos-base/src/View/Standard.php(263): Aimeos\Base\View\Standard->includeFile()
#4 /var/www/aimeos/vendor/aimeos/ai-controller-jobs/src/Controller/Jobs/Order/Email/Payment/Standard.php(346): Aimeos\Base\View\Standard->render()
#5 /var/www/aimeos/vendor/aimeos/ai-controller-jobs/src/Controller/Jobs/Order/Email/Payment/Standard.php(213): Aimeos\Controller\Jobs\Order\Email\Payment\Standard->send()
#6 /var/www/aimeos/vendor/aimeos/ai-controller-jobs/src/Controller/Jobs/Order/Email/Payment/Standard.php(128): Aimeos\Controller\Jobs\Order\Email\Payment\Standard->notify()
#7 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(54): Aimeos\Controller\Jobs\Order\Email\Payment\Standard->run()
#8 [internal function]: Aimeos\Shop\Command\JobsCommand->Aimeos\Shop\Command\closure()
#9 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(181): call_user_func_array()
#10 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(116): Aimeos\Base\Process\Pcntl->exec()
#11 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Decorator/Check.php(61): Aimeos\Base\Process\Pcntl->start()
#12 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(63): Aimeos\Base\Process\Decorator\Check->start()
#13 [internal function]: Aimeos\Shop\Command\JobsCommand->Aimeos\Shop\Command\closure()
#14 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(181): call_user_func_array()
#15 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(116): Aimeos\Base\Process\Pcntl->exec()
#16 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Decorator/Check.php(61): Aimeos\Base\Process\Pcntl->start()
#17 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/AbstractCommand.php(67): Aimeos\Base\Process\Decorator\Check->start()
#18 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(69): Aimeos\Shop\Command\AbstractCommand->exec()
#19 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Aimeos\Shop\Command\JobsCommand->handle()
#20 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\closure()
#21 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#22 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#23 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()
#24 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#25 /var/www/aimeos/vendor/symfony/console/Command/Command.php(291): Illuminate\Console\Command->execute()
#26 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#27 /var/www/aimeos/vendor/symfony/console/Application.php(989): Illuminate\Console\Command->run()
#28 /var/www/aimeos/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#29 /var/www/aimeos/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#30 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#31 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#32 /var/www/aimeos/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#33 main
```

**Comment by liviusirbulescu** [comment]
Also `Not allowed to access "controller/jobs/order/email/payment/pdf-partial" configuration`
```
Error while trying to send payment e-mail for order ID "9" and status "5": Not allowed to access "controller/jobs/order/email/payment/pdf-partial" configuration
#0 /var/www/aimeos/vendor/aimeos/aimeos-base/src/View/Helper/Config/Standard.php(50): Aimeos\Base\Config\Decorator\Protect->get()
#1 [internal function]: Aimeos\Base\View\Helper\Config\Standard->transform()
#2 /var/www/aimeos/vendor/aimeos/aimeos-base/src/View/Standard.php(87): call_user_func_array()
#3 /var/www/aimeos/vendor/aimeos/ai-controller-jobs/templates/order/email/payment/pdf.php(202): Aimeos\Base\View\Standard->__call()
#4 /var/www/aimeos/vendor/aimeos/aimeos-base/src/View/Standard.php(281): include('...')
#5 /var/www/aimeos/vendor/aimeos/aimeos-base/src/View/Standard.php(263): Aimeos\Base\View\Standard->includeFile()
#6 /var/www/aimeos/vendor/aimeos/ai-controller-jobs/src/Controller/Jobs/Order/Email/Payment/Standard.php(266): Aimeos\Base\View\Standard->render()
#7 /var/www/aimeos/vendor/aimeos/ai-controller-jobs/src/Controller/Jobs/Order/Email/Payment/Standard.php(348): Aimeos\Controller\Jobs\Order\Email\Payment\Standard->pdf()
#8 /var/www/aimeos/vendor/aimeos/ai-controller-jobs/src/Controller/Jobs/Order/Email/Payment/Standard.php(213): Aimeos\Controller\Jobs\Order\Email\Payment\Standard->send()
#9 /var/www/aimeos/vendor/aimeos/ai-controller-jobs/src/Controller/Jobs/Order/Email/Payment/Standard.php(128): Aimeos\Controller\Jobs\Order\Email\Payment\Standard->notify()
#10 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(54): Aimeos\Controller\Jobs\Order\Email\Payment\Standard->run()
#11 [internal function]: Aimeos\Shop\Command\JobsCommand->Aimeos\Shop\Command\closure()
#12 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(181): call_user_func_array()
#13 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(116): Aimeos\Base\Process\Pcntl->exec()
#14 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Decorator/Check.php(61): Aimeos\Base\Process\Pcntl->start()
#15 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(63): Aimeos\Base\Process\Decorator\Check->start()
#16 [internal function]: Aimeos\Shop\Command\JobsCommand->Aimeos\Shop\Command\closure()
#17 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(181): call_user_func_array()
#18 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Pcntl.php(116): Aimeos\Base\Process\Pcntl->exec()
#19 /var/www/aimeos/vendor/aimeos/aimeos-base/src/Process/Decorator/Check.php(61): Aimeos\Base\Process\Pcntl->start()
#20 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/AbstractCommand.php(67): Aimeos\Base\Process\Decorator\Check->start()
#21 /var/www/aimeos/vendor/aimeos/aimeos-laravel/src/Aimeos/Shop/Command/JobsCommand.php(69): Aimeos\Shop\Command\AbstractCommand->exec()
#22 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Aimeos\Shop\Command\JobsCommand->handle()
#23 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\closure()
#24 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#25 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#26 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()
#27 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#28 /var/www/aimeos/vendor/symfony/console/Command/Command.php(291): Illuminate\Console\Command->execute()
#29 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#30 /var/www/aimeos/vendor/symfony/console/Application.php(989): Illuminate\Console\Command->run()
#31 /var/www/aimeos/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#32 /var/www/aimeos/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#33 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#34 /var/www/aimeos/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#35 /var/www/aimeos/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#36 main
```

**Comment by aimeos** [comment]
Removed the old link in the e-mail template and added the config to the white list. You have to update the Aimeos Laravel package too:
```
composer req aimeos/aimeos-laravel:2022.04.x-dev aimeos/ai-controller-jobs:2022.04.x.dev
```
We will rewrite the config white list thing because it's getting to restrictive.

**Comment by liviusirbulescu** [comment]
I can confirm delivery and payment emails are coming through on aimeos/aimeos-laravel:2022.04.x-dev aimeos/ai-controller-jobs:2022.04.x.dev
Looks like the correct logo (custom) is being used on the delivery emails but not on the payment ones (defaults to cid:5aee2354a7c00f1eaa2a90fc8cc886c2@symfony)

**Comment by aimeos** [comment]
Great! The code for the logos is exactly the same in both e-mails, the payment e-mail only contains a PDF attachment in addition. Does the payment email contains both attachments (PDF and logo) and is the CID file name of the logo `5aee2354a7c00f1eaa2a90fc8cc886c2@symfony`?

**Comment by liviusirbulescu** [comment]
Thanks again for your quick replies, much appreciated.
The payment email contains only the PDF, sorry I should've mentioned this, MailHog snippet below

![image](https://user-images.githubusercontent.com/37197195/170476926-7cab93b6-8598-4396-9b34-f6eb700e0f74.png)

**Comment by aimeos** [comment]
Can you please investigate a bit further and test if that also happens if the PDF isn't attached?
https://github.com/aimeos/ai-controller-jobs/blob/2022.04/src/Controller/Jobs/Order/Email/Payment/Standard.php#L348

**Comment by liviusirbulescu** [comment]
Please ignore the payment emails logo issue, applies only to my local env, everything works as expected on my staging server.
Thanks again for all your quick replies and great work on aimeos project.

**Comment by aimeos** [comment]
Thank your for your help to find the issues. Much appreciated!
We will tag new versions soon.
